// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/env.ts
var getEnv = (name) => {
  const value = process.env[name];
  if (!value) throw new Error(`Missing env var: ${name}`);
  return value;
};

// src/lib/mcp/tools/list-blog-posts.ts
function supabaseForUser(ctx) {
  return createClient(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List blog posts from the ClickOne blog. Returns id, title, slug, status, published_at and views.",
  inputSchema: {
    status: z.enum(["draft", "published", "archived", "all"]).optional().describe("Filter by post status. Defaults to published."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blog_posts").select("id, title, slug, status, published_at, views").order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (!status || status !== "all") {
      query = query.eq("status", status ?? "published");
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single blog post by slug, including its full content.",
  inputSchema: {
    slug: z2.string().min(1).describe("The blog post slug, e.g. 'meu-post'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No post found with slug '${slug}'.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool3({
  name: "list_leads",
  title: "List leads",
  description: "List recent leads captured by the ClickOne site. Requires admin access; RLS enforces this on the database side.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("leads").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool4({
  name: "get_lead",
  title: "Get lead",
  description: "Fetch a single lead by id or email. Requires admin access via RLS.",
  inputSchema: {
    id: z4.string().uuid().optional().describe("Lead UUID."),
    email: z4.string().email().optional().describe("Lead email.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, email }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !email) {
      return { content: [{ type: "text", text: "Provide id or email." }], isError: true };
    }
    let query = supabaseForUser4(ctx).from("leads").select("*").limit(1);
    if (id) query = query.eq("id", id);
    else if (email) query = query.eq("email", email);
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_lead_default = defineTool5({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new lead in the ClickOne CRM. Requires at least an email. Optional fields: name, phone, company, source, utm_source, utm_medium, utm_campaign, status.",
  inputSchema: {
    email: z5.string().email().describe("Lead email (required)."),
    name: z5.string().optional(),
    phone: z5.string().optional(),
    company: z5.string().optional(),
    source: z5.string().optional().describe("Where the lead came from (e.g. 'mcp', 'landing-page')."),
    utm_source: z5.string().optional(),
    utm_medium: z5.string().optional(),
    utm_campaign: z5.string().optional(),
    status: z5.string().optional().describe("Lead status (default 'new').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("leads").insert({ ...input, source: input.source ?? "mcp" }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_lead_status_default = defineTool6({
  name: "update_lead_status",
  title: "Update lead status",
  description: "Update the status of an existing lead by id. Common values: 'new', 'contacted', 'qualified', 'converted', 'lost'. Requires admin access via RLS.",
  inputSchema: {
    id: z6.string().uuid().describe("Lead UUID."),
    status: z6.string().min(1).describe("New status value.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("leads").update({ status }).eq("id", id).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function slugify(input) {
  return input.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-").replace(/-+/g, "-").slice(0, 80);
}
var create_blog_post_default = defineTool7({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Create a new blog post. Provide title and content (Markdown or HTML). Slug is auto-generated from the title if omitted. Set status='published' to publish immediately (published_at is set to now); otherwise it stays as draft. Requires admin (RLS).",
  inputSchema: {
    title: z7.string().min(3).describe("Post title."),
    content: z7.string().min(10).describe("Full post body (Markdown or HTML)."),
    slug: z7.string().optional().describe("URL slug. Auto-generated from title if omitted."),
    excerpt: z7.string().optional().describe("Short summary shown in listings."),
    cover_image: z7.string().url().optional().describe("Cover image URL."),
    category_id: z7.string().uuid().optional(),
    author: z7.string().optional(),
    status: z7.enum(["draft", "published"]).optional().describe("Default 'draft'."),
    meta_title: z7.string().optional(),
    meta_description: z7.string().optional(),
    read_time: z7.number().int().min(1).max(120).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const status = input.status ?? "draft";
    const slug = input.slug?.trim() || slugify(input.title);
    const row = {
      title: input.title,
      slug,
      content: input.content,
      excerpt: input.excerpt,
      cover_image: input.cover_image,
      category_id: input.category_id,
      author: input.author,
      status,
      published_at: status === "published" ? (/* @__PURE__ */ new Date()).toISOString() : null,
      meta_title: input.meta_title,
      meta_description: input.meta_description,
      read_time: input.read_time
    };
    const { data, error } = await supabaseForUser7(ctx).from("blog_posts").insert(row).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/update-blog-post.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^3.25.76";
function supabaseForUser8(ctx) {
  return createClient8(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function slugify2(input) {
  return input.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-").replace(/-+/g, "-").slice(0, 80);
}
var update_blog_post_default = defineTool8({
  name: "update_blog_post",
  title: "Update blog post",
  description: "Update an existing blog post by id or current slug. Any field (title, slug, content, excerpt, cover_image, meta_*, read_time) may be omitted to keep the current value. Toggle publish state with status='draft'|'published' \u2014 switching to 'published' sets published_at=now if it was empty; switching to 'draft' clears published_at. Requires admin (RLS).",
  inputSchema: {
    id: z8.string().uuid().optional().describe("Post id. Provide id OR slug."),
    slug: z8.string().optional().describe("Current slug. Provide id OR slug."),
    title: z8.string().min(3).optional(),
    new_slug: z8.string().optional().describe("New URL slug. If omitted, slug is unchanged."),
    content: z8.string().min(10).optional(),
    excerpt: z8.string().optional(),
    cover_image: z8.string().url().optional(),
    category_id: z8.string().uuid().optional(),
    author: z8.string().optional(),
    status: z8.enum(["draft", "published"]).optional(),
    meta_title: z8.string().optional(),
    meta_description: z8.string().optional(),
    read_time: z8.number().int().min(1).max(120).optional(),
    regenerate_slug_from_title: z8.boolean().optional().describe("If true and new_slug omitted, regenerate slug from the (new or existing) title.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!input.id && !input.slug) {
      return { content: [{ type: "text", text: "Provide either id or slug." }], isError: true };
    }
    const supabase = supabaseForUser8(ctx);
    const q = supabase.from("blog_posts").select("*").limit(1);
    const { data: existing, error: fetchErr } = input.id ? await q.eq("id", input.id).maybeSingle() : await q.eq("slug", input.slug).maybeSingle();
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "Post not found." }], isError: true };
    const patch = {};
    if (input.title !== void 0) patch.title = input.title;
    if (input.content !== void 0) patch.content = input.content;
    if (input.excerpt !== void 0) patch.excerpt = input.excerpt;
    if (input.cover_image !== void 0) patch.cover_image = input.cover_image;
    if (input.category_id !== void 0) patch.category_id = input.category_id;
    if (input.author !== void 0) patch.author = input.author;
    if (input.meta_title !== void 0) patch.meta_title = input.meta_title;
    if (input.meta_description !== void 0) patch.meta_description = input.meta_description;
    if (input.read_time !== void 0) patch.read_time = input.read_time;
    if (input.new_slug) {
      patch.slug = input.new_slug.trim();
    } else if (input.regenerate_slug_from_title) {
      patch.slug = slugify2(input.title ?? existing.title);
    }
    if (input.status !== void 0 && input.status !== existing.status) {
      patch.status = input.status;
      if (input.status === "published") {
        if (!existing.published_at) patch.published_at = (/* @__PURE__ */ new Date()).toISOString();
      } else {
        patch.published_at = null;
      }
    }
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No changes provided." }], isError: true };
    }
    const { data, error } = await supabase.from("blog_posts").update(patch).eq("id", existing.id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data, changed_fields: Object.keys(patch) }
    };
  }
});

// src/lib/mcp/tools/preview-blog-post.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z9 } from "npm:zod@^3.25.76";
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function renderInline(text) {
  let s = escapeHtml(text);
  s = s.replace(
    /!\[([^\]]*)\]\(([^)\s]+)(?:\s+"([^"]*)")?\)/g,
    (_m, alt, url, title) => `<img src="${url}" alt="${alt}"${title ? ` title="${title}"` : ""} />`
  );
  s = s.replace(
    /\[([^\]]+)\]\(([^)\s]+)(?:\s+"([^"]*)")?\)/g,
    (_m, t, url, title) => `<a href="${url}"${title ? ` title="${title}"` : ""}>${t}</a>`
  );
  s = s.replace(/`([^`]+)`/g, (_m, c) => `<code>${c}</code>`);
  s = s.replace(/(\*\*|__)(.+?)\1/g, "<strong>$2</strong>");
  s = s.replace(/(^|[\s(])(\*|_)([^*_\n]+)\2/g, "$1<em>$3</em>");
  return s;
}
function renderMarkdown(md) {
  if (/^\s*<[a-zA-Z!]/.test(md)) return md;
  const lines = md.replace(/\r\n?/g, "\n").split("\n");
  const out = [];
  let i = 0;
  let inList = null;
  const closeList = () => {
    if (inList) {
      out.push(`</${inList}>`);
      inList = null;
    }
  };
  while (i < lines.length) {
    const line = lines[i];
    const fence = line.match(/^```(\w*)\s*$/);
    if (fence) {
      closeList();
      const lang = fence[1] || "";
      const buf2 = [];
      i++;
      while (i < lines.length && !/^```\s*$/.test(lines[i])) {
        buf2.push(lines[i]);
        i++;
      }
      i++;
      out.push(`<pre><code${lang ? ` class="language-${lang}"` : ""}>${escapeHtml(buf2.join("\n"))}</code></pre>`);
      continue;
    }
    if (/^\s*$/.test(line)) {
      closeList();
      i++;
      continue;
    }
    const h = line.match(/^(#{1,6})\s+(.*)$/);
    if (h) {
      closeList();
      out.push(`<h${h[1].length}>${renderInline(h[2])}</h${h[1].length}>`);
      i++;
      continue;
    }
    if (/^\s*(?:---|\*\*\*|___)\s*$/.test(line)) {
      closeList();
      out.push("<hr />");
      i++;
      continue;
    }
    if (/^>\s?/.test(line)) {
      closeList();
      const buf2 = [];
      while (i < lines.length && /^>\s?/.test(lines[i])) {
        buf2.push(lines[i].replace(/^>\s?/, ""));
        i++;
      }
      out.push(`<blockquote>${renderInline(buf2.join(" "))}</blockquote>`);
      continue;
    }
    if (/^\s*[-*+]\s+/.test(line)) {
      if (inList !== "ul") {
        closeList();
        out.push("<ul>");
        inList = "ul";
      }
      out.push(`<li>${renderInline(line.replace(/^\s*[-*+]\s+/, ""))}</li>`);
      i++;
      continue;
    }
    if (/^\s*\d+\.\s+/.test(line)) {
      if (inList !== "ol") {
        closeList();
        out.push("<ol>");
        inList = "ol";
      }
      out.push(`<li>${renderInline(line.replace(/^\s*\d+\.\s+/, ""))}</li>`);
      i++;
      continue;
    }
    closeList();
    const buf = [line];
    i++;
    while (i < lines.length && !/^\s*$/.test(lines[i]) && !/^(#{1,6}\s|>|```|\s*[-*+]\s+|\s*\d+\.\s+)/.test(lines[i])) {
      buf.push(lines[i]);
      i++;
    }
    out.push(`<p>${renderInline(buf.join(" "))}</p>`);
  }
  closeList();
  return out.join("\n");
}
function stripHtml(html) {
  return html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&nbsp;/g, " ").replace(/\s+/g, " ").trim();
}
function estimateReadTime(plainText, wpm = 220) {
  const words = plainText ? plainText.split(/\s+/).filter(Boolean).length : 0;
  return { words, read_time_minutes: Math.max(1, Math.round(words / wpm)) };
}
var preview_blog_post_default = defineTool9({
  name: "preview_blog_post",
  title: "Preview blog post",
  description: "Render a blog post preview WITHOUT saving. Converts Markdown to HTML (or passes HTML through), returns a plain-text excerpt, word count, and estimated read time (minutes). Use before `create_blog_post` or `update_blog_post` to review output. `intended_status` and `intended_slug` are echoed back so agents can chain into a save call.",
  inputSchema: {
    title: z9.string().min(1),
    content: z9.string().min(1).describe("Markdown or HTML."),
    excerpt: z9.string().optional(),
    intended_status: z9.enum(["draft", "published"]).optional(),
    intended_slug: z9.string().optional(),
    words_per_minute: z9.number().int().min(80).max(400).optional().describe("Reading speed (default 220 wpm).")
  },
  annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const html = renderMarkdown(input.content);
    const plain = stripHtml(html);
    const { words, read_time_minutes } = estimateReadTime(plain, input.words_per_minute ?? 220);
    const auto_excerpt = input.excerpt?.trim() || (plain.length > 200 ? plain.slice(0, 200).trim() + "\u2026" : plain);
    const characters = plain.length;
    const preview = {
      title: input.title,
      intended_status: input.intended_status ?? "draft",
      intended_slug: input.intended_slug,
      html,
      plain_text: plain,
      excerpt: auto_excerpt,
      stats: { words, characters, read_time_minutes }
    };
    return {
      content: [
        {
          type: "text",
          text: `Preview of "${input.title}"
Status (intended): ${preview.intended_status}
Slug (intended): ${preview.intended_slug ?? "(auto from title)"}
Words: ${words} \u2022 Read time: ~${read_time_minutes} min

Excerpt: ${auto_excerpt}

--- HTML ---
${html}`
        }
      ],
      structuredContent: preview
    };
  }
});

// src/lib/mcp/tools/schedule-demo.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z10 } from "npm:zod@^3.25.76";
function supabaseAnon() {
  return createClient9(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseService() {
  return createClient9(getEnv("SUPABASE_URL"), getEnv("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function sendConfirmationEmail(params) {
  const lovableKey = getEnv("LOVABLE_API_KEY");
  const resendKey = getEnv("RESEND_API_KEY");
  const when = new Date(params.scheduledAt).toLocaleString("pt-BR", {
    timeZone: params.timezone,
    dateStyle: "full",
    timeStyle: "short"
  });
  const html = `
    <div style="font-family:Arial,sans-serif;max-width:560px;margin:0 auto;padding:24px;background:#ffffff;color:#111827">
      <h1 style="color:#7c3aed;margin:0 0 12px">Demonstra\xE7\xE3o ClickOne Pro confirmada</h1>
      <p>Ol\xE1${params.name ? ` ${params.name}` : ""},</p>
      <p>Sua demonstra\xE7\xE3o est\xE1 agendada para:</p>
      <p style="font-size:18px;font-weight:600;background:#f5f3ff;padding:12px 16px;border-radius:8px;color:#4c1d95">${when}</p>
      ${params.notes ? `<p><strong>Observa\xE7\xF5es:</strong> ${params.notes}</p>` : ""}
      <p>Nossa equipe entrar\xE1 em contato para confirmar os detalhes. Se precisar reagendar, responda este e-mail.</p>
      <p style="margin-top:24px;color:#6b7280;font-size:13px">\u2014 Equipe ClickOne Pro \xB7 https://clickonepro.com</p>
    </div>`.trim();
  const res = await fetch("https://connector-gateway.lovable.dev/resend/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${lovableKey}`,
      "X-Connection-Api-Key": resendKey
    },
    body: JSON.stringify({
      from: "ClickOne Pro <onboarding@resend.dev>",
      to: [params.to],
      subject: "Sua demonstra\xE7\xE3o ClickOne Pro est\xE1 agendada",
      html
    })
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Resend ${res.status}: ${body}`);
  }
  return true;
}
var schedule_demo_default = defineTool10({
  name: "schedule_demo",
  title: "Schedule demo",
  description: "Register a demo booking for a lead and send a confirmation email. Auto-creates or updates the linked lead (status \u2192 'demo_scheduled'). Public tool: no login required.",
  inputSchema: {
    email: z10.string().email().describe("Lead email (required)."),
    scheduled_at: z10.string().datetime().describe("ISO 8601 date-time of the demo (e.g. 2026-07-25T14:00:00Z)."),
    name: z10.string().optional(),
    phone: z10.string().optional(),
    company: z10.string().optional(),
    timezone: z10.string().optional().describe("IANA timezone. Default 'America/Sao_Paulo'."),
    notes: z10.string().optional(),
    send_confirmation: z10.boolean().optional().describe("Send confirmation email (default true).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input, _ctx) => {
    const timezone = input.timezone ?? "America/Sao_Paulo";
    const anon = supabaseAnon();
    const service = supabaseService();
    const { data: existingLead } = await service.from("leads").select("id").eq("email", input.email).maybeSingle();
    let leadId = existingLead?.id;
    if (leadId) {
      await service.from("leads").update({
        status: "demo_scheduled",
        name: input.name ?? void 0,
        phone: input.phone ?? void 0,
        company: input.company ?? void 0
      }).eq("id", leadId);
    } else {
      const { data: newLead, error: leadErr } = await service.from("leads").insert({
        email: input.email,
        name: input.name,
        phone: input.phone,
        company: input.company,
        source: "mcp:schedule_demo",
        status: "demo_scheduled"
      }).select("id").single();
      if (leadErr) {
        return { content: [{ type: "text", text: `Lead upsert failed: ${leadErr.message}` }], isError: true };
      }
      leadId = newLead.id;
    }
    const { data: booking, error: bookErr } = await anon.from("demo_bookings").insert({
      lead_id: leadId,
      email: input.email,
      name: input.name,
      phone: input.phone,
      company: input.company,
      scheduled_at: input.scheduled_at,
      timezone,
      notes: input.notes,
      source: "mcp",
      status: "scheduled"
    }).select().single();
    if (bookErr) {
      return { content: [{ type: "text", text: `Booking insert failed: ${bookErr.message}` }], isError: true };
    }
    let emailSent = false;
    let emailError;
    if (input.send_confirmation !== false) {
      try {
        await sendConfirmationEmail({
          to: input.email,
          name: input.name,
          scheduledAt: input.scheduled_at,
          timezone,
          notes: input.notes
        });
        emailSent = true;
        await service.from("demo_bookings").update({ confirmation_sent_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", booking.id);
      } catch (err) {
        emailError = err instanceof Error ? err.message : String(err);
      }
    }
    const summary = {
      booking_id: booking.id,
      lead_id: leadId,
      scheduled_at: input.scheduled_at,
      timezone,
      email_sent: emailSent,
      email_error: emailError
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ojyzegzdlpjlbdhvqhav";
var mcp_default = defineMcp({
  name: "clickonepro-mcp",
  title: "ClickOne Pro MCP",
  version: "0.5.0",
  instructions: "Tools for the ClickOne Pro CRM and blog. Blog (admin write): `list_blog_posts`, `get_blog_post`, `create_blog_post`, `update_blog_post`. Blog utility (no auth needed): `preview_blog_post` renders Markdown\u2192HTML and estimates read_time before saving. Leads (admin): `list_leads`, `get_lead`, `create_lead`, `update_lead_status`. Public: `schedule_demo` books a demo and emails a confirmation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_blog_posts_default,
    get_blog_post_default,
    create_blog_post_default,
    update_blog_post_default,
    preview_blog_post_default,
    list_leads_default,
    get_lead_default,
    create_lead_default,
    update_lead_status_default,
    schedule_demo_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
