// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/env.ts
var getEnv = (name) => {
  const value = process.env[name];
  if (!value) throw new Error(`Missing env var: ${name}`);
  return value;
};

// src/lib/mcp/tools/list-blog-posts.ts
function supabaseForUser(ctx) {
  return createClient(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List blog posts from the ClickOne blog. Returns id, title, slug, status, published_at and views.",
  inputSchema: {
    status: z.enum(["draft", "published", "archived", "all"]).optional().describe("Filter by post status. Defaults to published."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blog_posts").select("id, title, slug, status, published_at, views").order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (!status || status !== "all") {
      query = query.eq("status", status ?? "published");
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single blog post by slug, including its full content.",
  inputSchema: {
    slug: z2.string().min(1).describe("The blog post slug, e.g. 'meu-post'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No post found with slug '${slug}'.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool3({
  name: "list_leads",
  title: "List leads",
  description: "List recent leads captured by the ClickOne site. Requires admin access; RLS enforces this on the database side.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("leads").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool4({
  name: "get_lead",
  title: "Get lead",
  description: "Fetch a single lead by id or email. Requires admin access via RLS.",
  inputSchema: {
    id: z4.string().uuid().optional().describe("Lead UUID."),
    email: z4.string().email().optional().describe("Lead email.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, email }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !email) {
      return { content: [{ type: "text", text: "Provide id or email." }], isError: true };
    }
    let query = supabaseForUser4(ctx).from("leads").select("*").limit(1);
    if (id) query = query.eq("id", id);
    else if (email) query = query.eq("email", email);
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_lead_default = defineTool5({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new lead in the ClickOne CRM. Requires at least an email. Optional fields: name, phone, company, source, utm_source, utm_medium, utm_campaign, status.",
  inputSchema: {
    email: z5.string().email().describe("Lead email (required)."),
    name: z5.string().optional(),
    phone: z5.string().optional(),
    company: z5.string().optional(),
    source: z5.string().optional().describe("Where the lead came from (e.g. 'mcp', 'landing-page')."),
    utm_source: z5.string().optional(),
    utm_medium: z5.string().optional(),
    utm_campaign: z5.string().optional(),
    status: z5.string().optional().describe("Lead status (default 'new').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("leads").insert({ ...input, source: input.source ?? "mcp" }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_lead_status_default = defineTool6({
  name: "update_lead_status",
  title: "Update lead status",
  description: "Update the status of an existing lead by id. Common values: 'new', 'contacted', 'qualified', 'converted', 'lost'. Requires admin access via RLS.",
  inputSchema: {
    id: z6.string().uuid().describe("Lead UUID."),
    status: z6.string().min(1).describe("New status value.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("leads").update({ status }).eq("id", id).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function slugify(input) {
  return input.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-").replace(/-+/g, "-").slice(0, 80);
}
var create_blog_post_default = defineTool7({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Create a new blog post. Provide title and content (Markdown or HTML). Slug is auto-generated from the title if omitted. Set status='published' to publish immediately (published_at is set to now); otherwise it stays as draft. Requires admin (RLS).",
  inputSchema: {
    title: z7.string().min(3).describe("Post title."),
    content: z7.string().min(10).describe("Full post body (Markdown or HTML)."),
    slug: z7.string().optional().describe("URL slug. Auto-generated from title if omitted."),
    excerpt: z7.string().optional().describe("Short summary shown in listings."),
    cover_image: z7.string().url().optional().describe("Cover image URL."),
    category_id: z7.string().uuid().optional(),
    author: z7.string().optional(),
    status: z7.enum(["draft", "published"]).optional().describe("Default 'draft'."),
    meta_title: z7.string().optional(),
    meta_description: z7.string().optional(),
    read_time: z7.number().int().min(1).max(120).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const status = input.status ?? "draft";
    const slug = input.slug?.trim() || slugify(input.title);
    const row = {
      title: input.title,
      slug,
      content: input.content,
      excerpt: input.excerpt,
      cover_image: input.cover_image,
      category_id: input.category_id,
      author: input.author,
      status,
      published_at: status === "published" ? (/* @__PURE__ */ new Date()).toISOString() : null,
      meta_title: input.meta_title,
      meta_description: input.meta_description,
      read_time: input.read_time
    };
    const { data, error } = await supabaseForUser7(ctx).from("blog_posts").insert(row).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ojyzegzdlpjlbdhvqhav";
var mcp_default = defineMcp({
  name: "clickonepro-mcp",
  title: "ClickOne Pro MCP",
  version: "0.3.0",
  instructions: "Tools for the ClickOne Pro CRM and blog. Blog: `list_blog_posts`, `get_blog_post`, `create_blog_post` (admin). Leads (admin, RLS-enforced): `list_leads`, `get_lead`, `create_lead`, `update_lead_status`.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_blog_posts_default,
    get_blog_post_default,
    create_blog_post_default,
    list_leads_default,
    get_lead_default,
    create_lead_default,
    update_lead_status_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
